# Generated by Django 5.0.2 on 2024-02-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgetpasswordrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='DurlData',
        ),
        migrations.DeleteModel(
            name='ForgetPasswordRequest',
        ),
    ]
